### ISSUE TITLE
Fix imports

### ISSUE THREAD

**Issue by ericelliott** [ericelliott/redux-dsm#4]
This is an ES6 module, meaning that you can't just import it in Node and start using it. You have to transpile or use `babel-core/register` prior to attempting to import it. Since this is a general-purpose library, I think the right approach is to switch to CommonJS module format, which AFAIK, is supported natively by Node, browserify, webpack, and JSPM, which I think covers all of the most common package managers in use today.

Todo:
* [ ] 1. `package.json` needs to point to `source/dsm.js` 
* [ ] 2. Swap out `import`/`export` with `require`/`module.exports`.  ([example](https://github.com/ericelliott/dpath/blob/a30d5a21cb51ca3a248453b9956be709a9a25c0b/source/index.js#L16)).
* [ ] 3. No build step needed! Compiling for the intended targets is a job for the module users, not for us. We don't know the intended targets, so we don't know the right options to build for. If we give them the raw source, it gives users the flexibility and freedom they need to decide things like whether or not they need to bundle a generator runtime, etc...

**Comment by ericelliott** [comment]
@zouhir All yours. Anxiously awaiting PR. =)

**Comment by ericelliott** [comment]
published

**Comment by Sigmus** [comment]
Should ```babel-cli``` in devDependencies and ```.babelrc``` also be removed?

**Comment by zouhir** [comment]
No, even tho the recommendations were to not have a build step here, Tape needs Babel to run the tests against our dsm.js that has ES6 generators and other ES6 stuff.

**Comment by ericelliott** [comment]
Hmm.. I pulled in Babel just for the `import` support. Since we're using Node 6 for the build, and we've switched to CommonJS modules, @Sigmus may be right.
